name: Build + Test + Benchmark

on:
  push:
    branches:
      - main

env:
  CC: clang-18
  CXX: clang++-18

  REPO_DIR: ${{github.workspace}}/repo
  BUILD_DIR: ${{github.workspace}}/build

  LEADERBOARD: https://sigmod-contest-25.hpi-sci.de

  CURL_CMD: "curl -X POST --fail-with-body -F github_user=${{github.actor}} -F github_repository=${{github.repository}} -F project_id=3 -F secret=${{secrets.HDP_SECRET}}"

  BM_RESULT_FILE: BENCHMARK_RUNTIME.txt


jobs:
  run_simple_checks:
    name: Build + Test + Benchmark

    strategy:
      fail-fast: false
      matrix:
        arch: [amd, arm, ibm, intel, amd2, arm2, ibm2, intel2]

    defaults:
      run:
        shell: bash

    runs-on: [self-hosted, sigmod, "${{ matrix.arch }}"]
    env:
      # We cannot obtain the runner name on some hosts. Use a fallback for now.
      FALLBACK_RUNNER_NAME: "sigmod-cp02-abcd"
    steps:
      - uses: actions/checkout@v3
        with:
          # Clones the repository to the subdir `repo`.
          path: repo

      - name: Copy Evaluation Files
        working-directory: ${{env.REPO_DIR}}
        run: |
          curl -u "${{secrets.NEXTCLOUD_KEY}}" -H "X-Requested-With:XMLHttpRequest" "https://nextcloud.hpi.de/public.php/webdav/" -o server_files.zip
          unzip -o -P "${{secrets.SERVER_FILES_PW}}" server_files.zip
          mv duckdb/imdb.db .

      - name: Copy Hardware Header
        run: cp $REPO_DIR/include/hardware__`hostname`.h $REPO_DIR/include/hardware.h

      - name: Create Build Environment
        run: cmake -E make_directory $BUILD_DIR

      - name: Configure CMake
        run: cmake -S $REPO_DIR -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=Release -Wno-dev -G Ninja

      - name: Build
        working-directory: ${{env.BUILD_DIR}}
        run: ninja

      - name: Run Unit Tests
        working-directory: ${{env.BUILD_DIR}}
        # Only allow test run of 30 seconds.
        run: |
          timeout 30 ./unit_tests
          EXIT_CODE=$?
          $CURL_CMD -F result=$EXIT_CODE -F runner_name=${RUNNER_NAME:-$FALLBACK_RUNNER_NAME} -F arch=${{ matrix.arch }} -F labels=${{ runner.labels }} -F git_commit=${{github.sha}} $LEADERBOARD/deliver_basic
          exit $EXIT_CODE

      - name: Run Evaluation
        if: matrix.arch == 'amd2'
        working-directory: ${{env.REPO_DIR}}
        run: |
          numactl -m 0 -N 0 ${{env.BUILD_DIR}}/run plans.json $BM_RESULT_FILE
          EXIT_CODE=$?
          $CURL_CMD -F runtime=`cat $BM_RESULT_FILE` -F runner_name=${RUNNER_NAME:-$FALLBACK_RUNNER_NAME} -F arch=${{ matrix.arch }} -F labels=${{ runner.labels }} -F git_commit=${{github.sha}} $LEADERBOARD/deliver_full_benchmark
          exit $EXIT_CODE

      - name: Run Evaluation
        if: matrix.arch != 'amd2'
        working-directory: ${{env.REPO_DIR}}
        run: |
          LD_LIBRARY_PATH=/usr/local/lib numactl -m 0 -N 0 ${{env.BUILD_DIR}}/run plans.json $BM_RESULT_FILE
          EXIT_CODE=$?
          $CURL_CMD -F runtime=`cat $BM_RESULT_FILE` -F runner_name=${RUNNER_NAME:-$FALLBACK_RUNNER_NAME} -F arch=${{ matrix.arch }} -F labels=${{ runner.labels }} -F git_commit=${{github.sha}} $LEADERBOARD/deliver_full_benchmark
          exit $EXIT_CODE
      - name: Clean Up
        if: always()
        run: rm -rf $REPO_DIR $BUILD_DIR
